/**
 * Document Entity
 * Requirements: Content Management 2.1, 2.2, 2.3, 2.4, 2.5
 */

export type DocumentType = 'TEXT' | 'IMAGE' | 'AUDIO';

export interface DocumentEntityProps {
  id: string;
  workspaceId: string;
  userId: string;
  title: string;
  content: string;
  type: DocumentType;
  fileId: string | null;
  generationId: string | null;
  createdAt: Date;
  updatedAt: Date;
}

export class DocumentEntity {
  private props: DocumentEntityProps;

  constructor(props: DocumentEntityProps) {
    this.props = props;
  }

  getId(): string {
    return this.props.id;
  }

  getWorkspaceId(): string {
    return this.props.workspaceId;
  }

  getUserId(): string {
    return this.props.userId;
  }

  getTitle(): string {
    return this.props.title;
  }

  getContent(): string {
    return this.props.content;
  }

  getType(): DocumentType {
    return this.props.type;
  }

  getFileId(): string | null {
    return this.props.fileId;
  }

  getGenerationId(): string | null {
    return this.props.generationId;
  }

  getCreatedAt(): Date {
    return this.props.createdAt;
  }

  getUpdatedAt(): Date {
    return this.props.updatedAt;
  }

  /**
   * Check if document belongs to user
   */
  belongsToUser(userId: string): boolean {
    return this.props.userId === userId;
  }

  /**
   * Check if document belongs to workspace
   */
  belongsToWorkspace(workspaceId: string): boolean {
    return this.props.workspaceId === workspaceId;
  }

  /**
   * Update document title
   */
  updateTitle(title: string): void {
    this.props.title = title;
    this.props.updatedAt = new Date();
  }

  /**
   * Update document content
   */
  updateContent(content: string): void {
    this.props.content = content;
    this.props.updatedAt = new Date();
  }

  /**
   * Check if document has associated file
   */
  hasFile(): boolean {
    return this.props.fileId !== null;
  }

  /**
   * Check if document was generated by AI
   */
  isGenerated(): boolean {
    return this.props.generationId !== null;
  }

  toJSON(): DocumentEntityProps {
    return { ...this.props };
  }
}
