/**
 * Document Entity Tests
 * Requirements: Content Management 2.1, 2.2, 2.3, 2.4, 2.5
 */

import { describe, it, expect } from 'vitest';
import { DocumentEntity } from '../entities/Document';

describe('DocumentEntity', () => {
  const mockDocumentProps = {
    id: '123e4567-e89b-12d3-a456-426614174000',
    workspaceId: '123e4567-e89b-12d3-a456-426614174001',
    userId: '123e4567-e89b-12d3-a456-426614174002',
    title: 'Test Document',
    content: 'This is test content',
    type: 'TEXT' as const,
    fileId: null,
    generationId: '123e4567-e89b-12d3-a456-426614174003',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  };

  it('should create a document entity', () => {
    const document = new DocumentEntity(mockDocumentProps);

    expect(document.getId()).toBe(mockDocumentProps.id);
    expect(document.getTitle()).toBe(mockDocumentProps.title);
    expect(document.getContent()).toBe(mockDocumentProps.content);
    expect(document.getType()).toBe(mockDocumentProps.type);
  });

  it('should check if document belongs to user', () => {
    const document = new DocumentEntity(mockDocumentProps);

    expect(document.belongsToUser(mockDocumentProps.userId)).toBe(true);
    expect(document.belongsToUser('different-user-id')).toBe(false);
  });

  it('should check if document belongs to workspace', () => {
    const document = new DocumentEntity(mockDocumentProps);

    expect(document.belongsToWorkspace(mockDocumentProps.workspaceId)).toBe(
      true
    );
    expect(document.belongsToWorkspace('different-workspace-id')).toBe(false);
  });

  it('should update document title', () => {
    const document = new DocumentEntity(mockDocumentProps);
    const originalUpdatedAt = document.getUpdatedAt();

    // Wait a bit to ensure timestamp changes
    const newTitle = 'Updated Title';
    document.updateTitle(newTitle);

    expect(document.getTitle()).toBe(newTitle);
    expect(document.getUpdatedAt().getTime()).toBeGreaterThanOrEqual(
      originalUpdatedAt.getTime()
    );
  });

  it('should update document content', () => {
    const document = new DocumentEntity(mockDocumentProps);
    const originalUpdatedAt = document.getUpdatedAt();

    const newContent = 'Updated content';
    document.updateContent(newContent);

    expect(document.getContent()).toBe(newContent);
    expect(document.getUpdatedAt().getTime()).toBeGreaterThanOrEqual(
      originalUpdatedAt.getTime()
    );
  });

  it('should check if document has associated file', () => {
    const documentWithoutFile = new DocumentEntity(mockDocumentProps);
    expect(documentWithoutFile.hasFile()).toBe(false);

    const documentWithFile = new DocumentEntity({
      ...mockDocumentProps,
      fileId: '123e4567-e89b-12d3-a456-426614174004',
    });
    expect(documentWithFile.hasFile()).toBe(true);
  });

  it('should check if document was generated by AI', () => {
    const generatedDocument = new DocumentEntity(mockDocumentProps);
    expect(generatedDocument.isGenerated()).toBe(true);

    const manualDocument = new DocumentEntity({
      ...mockDocumentProps,
      generationId: null,
    });
    expect(manualDocument.isGenerated()).toBe(false);
  });

  it('should convert to JSON', () => {
    const document = new DocumentEntity(mockDocumentProps);
    const json = document.toJSON();

    expect(json).toEqual(mockDocumentProps);
  });
});
